### ISSUE TITLE
Proposal: Move TODO.md to issues on GitHub

### ISSUE THREAD

**Issue by asg017** [nickslevine/zebras#1]
First off, I love this tool, would love to contribute!

Personally, I like to work with GitHub issues rather than a [`TODO.md`](https://github.com/nickslevine/zebras/blob/master/TODO.md) file, since it's easier to reference in PR's/comments. Contributors could also comment on the issue if they want to work on it, which is a little harder to do in a committed file. Also, tagging issues with `feature` or `bug` can be pretty helpful!

**Comment by nickslevine** [comment]
@asg017 Hell yeah, please do! 

And thanks for the suggestion - I will convert the items in [TODO.md](https://github.com/nickslevine/zebras/blob/master/TODO.md) to tagged GitHub issues and also create a higher-level roadmap document.
