### ISSUE TITLE
Question about `head` and `tail`

### ISSUE THREAD

**Issue by amytych** [nickslevine/zebras#13]
It's not super straightforward that these methods print something as a string. Wouldn't it be more useful and clear to have them return a subset of `df` (similarly to `filter`)?

Then printing of `head` or `tail` could be done via `Z.print(Z.head(10, df))` which is more clear on the intent? Or it could also be encapsulated in print-specific helpers: `printHead` and `printTail`.

Side note, there is `console.log()` lingering in `tail`: https://github.com/nickslevine/zebras/blob/b670068ff6989e20dc711bfdf2471fd31b908520/zebras.js#L228

**Comment by nickslevine** [comment]
@amytych Totally agree. Will implement those changes. Also, thanks for pointing out the console.log() - I'll remove that.
