### ISSUE TITLE
Make zebras browser friendly

### ISSUE THREAD

**Issue by amytych** [nickslevine/zebras#14]
Right now Zebras is intended for use either in Jupyter notebook or in ObservableHQ. But there might be a value in allowing it to be used in the browser as well. To be able to use some of its methods inside web applications, etc.

It seems that it wouldn't be too difficult to make it happen, the main blocker right now seems to be that everything is in one file and it uses the file system: https://github.com/nickslevine/zebras/blob/b670068ff6989e20dc711bfdf2471fd31b908520/zebras.js#L1

An idea could be to modularise it exposing methods as individual exports. This also has the perk of improved maintainability going forward instead of cramming more functionality into one file. Similarly to how [Ramda is structured](https://github.com/ramda/ramda/tree/master/source).

It'd be also advised, maybe as next step and not right away, to introduce a build step to produce different kinds of dist bundles (es6, cjs, umd).

**Comment by nickslevine** [comment]
That all makes sense - great points! Will look into it this weekend.

**Comment by nickslevine** [comment]
Any of those sounds good - what do you prefer?

**Comment by amytych** [comment]
I'd prefer to finish the docs, it's also a good way for me to get to know the library better, then we can proceed with a build system producing the bundles we want. Does that sound good?

**Comment by nickslevine** [comment]
Sounds good to me. Let me know if I can do anything to help.
