### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by nickslevine** [nickslevine/zebras#21]

**Comment by nickslevine** [comment]
Create Typescript type definitions file. From what I've read the Ramda pipe function might not work with it but everything else should hopefully be fine.

**Comment by brunobasto** [comment]
Hey there! interesting library! Did you discarded the issue or did you manage to create the type definitions?

**Comment by nickslevine** [comment]
Hi Bruno, thanks for getting in touch. I did create type definitions - will
have a quick look for where I stored them.

**Comment by nemosmithasf** [comment]
Hello, just wanted to double check, were the types ever added to the library or does the library still not support TS?

**Comment by nickslevine** [comment]
@nemosmithasf - thanks for the reminder! this totally slipped my mind. will sort this.

**Comment by nickslevine** [comment]
@nemosmithasf: a type definitions file can be found here: https://github.com/nickslevine/zebras/blob/master/source/index.d.ts. 

Will work on getting them properly added to DefinitelyTyped.

**Comment by nickslevine** [comment]
@brunobasto see above (sorry for the delay!)

**Comment by nemosmithasf** [comment]
Thanks!

**Comment by nickslevine** [comment]
Added a PR to DefinitelyTyped here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51359

Will update the zebras README when accepted. 

cc: @amytych

**Comment by nickslevine** [comment]
Updated typings, moved the right place, and specified in package.json

**Comment by nemosmithasf** [comment]
Would you be able to publish a new version to NPM with the typing?

**Comment by nickslevine** [comment]
@nemosmithasf yep, on it now

**Comment by nickslevine** [comment]
Just published 0.0.19 to nom

**Comment by nemosmithasf** [comment]
Appreciate it!
