### ISSUE TITLE
Does not import data with a comma in them

### ISSUE THREAD

**Issue by badgerblue** [nickslevine/zebras#35]
Excel surrounds these with cases with quotations when it is in a CSV. Zebras seems to just ignore these rows of data. This could be a user error. Please comment if you know a fix.

**Comment by nickslevine** [comment]
Thanks! Will have a look this weekend and get back to you.

**Comment by nickslevine** [comment]
@badgerblue Should be fixed with the last push [6c4b982225b50d3fd4e1cf6aa063ac2f59f995f6]
