### ISSUE TITLE
(latest npm package) Does not import data with a comma in them 

### ISSUE THREAD

**Issue by techieshark** [nickslevine/zebras#39]
This issue appears fixed in the code but not in the npm release:
https://github.com/nickslevine/zebras/issues/35

The last package release was prior to that commit - https://www.npmjs.com/package/zebras

image from npm:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/1072292/74129529-e78c5c00-4c33-11ea-9bff-1b496d8cf97b.png">

Possible to get a new release?

**Comment by nickslevine** [comment]
Ah yes, my bad, thanks for pointing this out. Will do later today.

**Comment by nickslevine** [comment]
Have published, might take a bit of time to filter through, will close once it does
